# Generated by Django 4.1.1 on 2022-09-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_alter_image_image_entry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageModel',
        ),
    ]
